---
# Sandbox inventory tasks

- block:
    - block:
        - name: Create temporary file to store vagrant sandbox vms inventory
          tempfile:
            state: file
            suffix: .inventory.yml
          register: vagrant_sandbox_create_inventory_result

        - name: Setup fact with path to inventory
          set_fact:
            vagrant_sandbox_inventory: >-
              {{ vagrant_sandbox_create_inventory_result.path }}
      when:
        - vagrant_sandbox_state in ["started", "recreated"]
        - >-
          vagrant_sandbox_inventory is none
          or vagrant_sandbox_inventory | length == 0

    - name: Show inventory file path
      debug:
        msg: "{{ vagrant_sandbox_inventory }}"
      when: vagrant_sandbox_create_inventory_result is changed

    - name: Delete temporary file with vagrant sandbox vms inventory
      file:
        path: "{{ vagrant_sandbox_inventory }}"
        state: absent
      when: vagrant_sandbox_state == "absent"
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::inventory
