---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 7
      debian: 9
      fedora: 27
      rhel: 7

- name: Sanity checks
  import_tasks: check.yml
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::check

- name: Load sandbox presets
  import_tasks: presets.yml
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::presets

- name: Get parent process id
  import_tasks: ppid.yml
  tags:
    - role::vagrant_sandbox

- name: Manage stalled containers
  import_tasks: stalled.yml
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::stalled

- name: Setup sandbox inventory
  import_tasks: inventory.yml
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::inventory

- name: Setup sandbox environment
  import_tasks: provision.yml
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::provision

- name: Run idempotence test
  import_tasks: idempotence.yml
  when: vagrant_sandbox_idempotence_test | bool
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::idempotence
