---
# Vagrant provision tasks

- block:
    - name: create virtual machines state information
      include_tasks: state.yml
      when: vagrant_sandbox_state in ["started", "recreated"]

    - name: provisione vagrant sandbox environment
      include_role:
        name: amtega.vagrant_provisioner
      vars:
        vagrant_provisioner_plugins: >-
          {{ (vagrant_sandbox_state in ["started", "recreated"])
             | ternary(vagrant_sandbox_plugins, []) }}
        vagrant_provisioner_boxes: >-
          {{ (vagrant_sandbox_state in ["started", "recreated"])
             | ternary(vagrant_sandbox_boxes, []) }}
        vagrant_provisioner_box_state: present
        vagrant_provisioner_vms: "{{ vagrant_sandbox_vms }}"
        vagrant_provisioner_vms_directory: "{{ vagrant_sandbox_vms_directory }}"
        vagrant_provisioner_vm_groups: ["{{ vagrant_sandbox_group }}"]
        vagrant_provisioner_inventory: >-
          {{ (vagrant_sandbox_state in ["started", "recreated"])
             | ternary(vagrant_sandbox_inventory, "") }}
        vagrant_provisioner_vm_state: >-
          {{ (vagrant_sandbox_state in ["recreated"])
             | ternary("started", vagrant_sandbox_state) }}
        vagrant_provisioner_vm_ansible_ssh_common_args: >-
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::provision
