---
# Sandbox parameters verification tasks

- name: check vagrant sandbox state value
  fail:
    msg: "vagrant_sandbox_state has an invalid value"
  when: vagrant_sandbox_state not in ["started", "recreated", "absent"]
  tags:
    - role::vagrant_sandbox
    - role::vagrant_sandbox::verify
