---
# Drop a sandbox environment

- name: Cleanup vagrant sandbox environment
  hosts: localhost
  vars_prompt:
    - name: vagrant_sandbox_inventory
      prompt: >-
        Enter absolute path to vagrant sandbox inventory file
        (if not given will try to cleanup all vagrant sandboxes)
      private: no
  roles:
    - role: amtega.vagrant_sandbox
      vagrant_sandbox_state: absent
